### ISSUE TITLE
Deprecated selector in `git-change-marker/styles/git-change-marker.less`

### ISSUE THREAD

**Issue by juvevood** [qzchenwl/git-change-marker#2]
In `git-change-marker/styles/git-change-marker.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.git-change-marker-toolbar atom-text-editor::shadow .lines > div > div` => `.git-change-marker-toolbar atom-text-editor.editor .lines > div > div`

* `atom-text-editor .gutter .line-number.git-line-modified,
atom-text-editor::shadow .gutter .line-number.git-line-modified,
atom-text-editor .gutter .line-number.git-line-added,
atom-text-editor::shadow .gutter .line-number.git-line-added,
atom-text-editor .gutter .line-number.git-line-removed,
atom-text-editor::shadow .gutter .line-number.git-line-removed` => `atom-text-editor .gutter .line-number.git-line-modified,
atom-text-editor.editor .gutter .line-number.git-line-modified,
atom-text-editor .gutter .line-number.git-line-added,
atom-text-editor.editor .gutter .line-number.git-line-added,
atom-text-editor .gutter .line-number.git-line-removed,
atom-text-editor.editor .gutter .line-number.git-line-removed`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Nicolab** [comment]
:+1:

**Comment by Nicolab** [comment]
@qzchenwl will be fixed?

**Comment by Nicolab** [comment]
@qzchenwl thanks!

**Comment by juvevood** [comment]
@qzchenwl thanks!
